### ISSUE TITLE
As an anti-populist I want to demonstrate to my populist friend that a certain text qualifies as populist [according to tony blair institute] so that I can try and convince them that the leader responsible for this text is populist. 21

### ISSUE THREAD

**Issue by AGolan84** [code4policy/2024-b4-inequality#22]

**Comment by LucNsabimana** [comment]
- [ ] **Independent:** This user story is independent because it stands alone in its goal to identify populist text, not requiring external context or information.
- [ ] 
- [ ] **Negotiable:** This user story is negotiable because it invites discussion and interpretation on what constitutes a populist text."
- [ ] 
- [ ] **Valuable:** This user story is valuable because it aims to provide a clear and practical framework for identifying populist rhetoric."
- [ ] 
- [ ] **Estimable:** This user story is estimable because the success of identifying a populist text can be measured against predefined criteria.
- [ ] 
- [ ] **Small:** This user story is small because it focuses on a specific task of assessing a text for populism, without unnecessary complexity.
- [ ] 
- [ ] **Testable:** This user story is testable because the criteria for populist content can be objectively applied and verified in different texts.

**Comment by LucNsabimana** [comment]
Definition of done:

- User can copy and paste any text in GPT4 & gets feedback whether text is populist or not

**Comment by AGolan84** [comment]
Reframed
